citys=['tokyo','hongKong','russia','washington','korea']
print('origin:',citys)
print('sorted:',sorted(citys))
print('after sorted:',citys)
print('sorted reverse:',sorted(citys,reverse=True))
print('after sorted reverse:',citys)
citys.reverse()
print('reverse after:',citys)
citys.reverse()
print('reverse again:',citys)
citys.sort()
print('sort after:',citys)
citys.sort(reverse=True)
print('sort reverse after:',citys)
print('there are',len(citys),'citys')